"""Export KiCad LED placement and firmware index tables from a city file.

Outputs:
  leds.csv           - LED index, reference, station, x/y (mm, board coords),
                       rotation (deg, DOUT pointing at the next LED in chain)
  firmware_tables.h  - NUM_LEDS + one LED-index array per line route + extras

The chain order comes from the city file's "chain" list (index 0 = first LED
after the level shifter). Firmware routes are derived from line paths: the
first path of a line is the trunk; each further path branches off a trunk
station, giving one full route per branch (trunk-to-branch-tip).

Usage:
    python export_placement.py ../input/vancouver.json ../hardware/ --scale 1.5
"""
import argparse
import json
import math
import os

import citymap


def load_chain(data_path, city):
    with open(data_path, encoding="utf-8") as f:
        chain = json.load(f).get("chain", [])
    all_ids = set(city.stations) | {e.id for e in city.extras}
    missing = all_ids - set(chain)
    dupes = [c for c in chain if chain.count(c) > 1]
    unknown = [c for c in chain if c not in all_ids]
    if missing or dupes or unknown:
        raise SystemExit(f"chain invalid: missing={sorted(missing)} "
                         f"dupes={dupes} unknown={unknown}")
    return chain


def station_of(city, sid):
    if sid in city.stations:
        return city.stations[sid]
    return next(e for e in city.extras if e.id == sid)


def led_rows(city, chain, scale):
    """[(index, ref, sid, name, x_mm, y_mm, rot_deg)] with rot aiming DOUT at
    the next LED (KiCad angle: 0 = east, counter-clockwise positive)."""
    rows = []
    for i, sid in enumerate(chain):
        st = station_of(city, sid)
        x, y = st.x * scale, st.y * scale
        if i + 1 < len(chain):
            nxt = station_of(city, chain[i + 1])
            dx, dy = nxt.x - st.x, nxt.y - st.y
        else:
            prv = station_of(city, chain[i - 1])
            dx, dy = st.x - prv.x, st.y - prv.y
        ang = (math.degrees(math.atan2(-dy, dx))) % 360  # y down -> KiCad CCW
        rot = round(ang / 45) * 45 % 360
        rows.append((i, f"LED{i + 1}", sid, st.name, round(x, 3),
                     round(y, 3), rot))
    return rows


def routes(city):
    """[(c_name, [station ids])] — one full route per line branch + extras."""
    out = []
    for line in city.lines:
        trunk = line.paths[0]
        base = line.id.upper().replace("-", "_")
        if len(line.paths) == 1:
            out.append((base, trunk))
            continue
        for branch in line.paths[1:]:
            fork = branch[0]
            if fork not in trunk:
                raise SystemExit(f"{line.id}: branch start '{fork}' not on trunk")
            route = trunk[:trunk.index(fork)] + branch
            out.append((f"{base}_{branch[-1].upper().replace('-', '_')}", route))
    for e in city.extras:
        out.append((e.id.upper().replace("-", "_"), [e.id]))
    return out


def write_csv(rows, path):
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("index,ref,station,name,x_mm,y_mm,rotation\n")
        for r in rows:
            f.write(",".join(str(v) for v in r) + "\n")


def write_header(city, chain, rows, path):
    idx = {sid: i for i, sid in enumerate(chain)}
    lines = ["// GENERATED by export_placement.py - do not edit by hand.",
             f"// City: {city.name}. LED index = position in data chain.",
             "#pragma once", "",
             f"const uint16_t NUM_LEDS = {len(chain)};", ""]
    for name, route in routes(city):
        ids = [idx[s] for s in route]
        lines.append(f"const int LINE_{name}_COUNT = {len(ids)};")
        lines.append(f"const int LINE_{name}[] = {{")
        for s in route:
            lines.append(f"    {idx[s]:3d}, // {station_of(city, s).name}")
        lines.append("};")
        lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("data")
    ap.add_argument("outdir")
    ap.add_argument("--scale", type=float, default=1.5)
    args = ap.parse_args()
    city = citymap.load(args.data)
    chain = load_chain(args.data, city)
    os.makedirs(args.outdir, exist_ok=True)
    rows = led_rows(city, chain, args.scale)
    write_csv(rows, os.path.join(args.outdir, "leds.csv"))
    write_header(city, chain, rows,
                 os.path.join(args.outdir, "firmware_tables.h"))
    hops = []
    for i in range(len(chain) - 1):
        a, b = station_of(city, chain[i]), station_of(city, chain[i + 1])
        hops.append((math.hypot(b.x - a.x, b.y - a.y) * args.scale,
                     chain[i], chain[i + 1]))
    hops.sort(reverse=True)
    print(f"wrote {len(rows)} LEDs to {args.outdir}")
    print("longest data hops (mm):")
    for d, a, b in hops[:5]:
        print(f"  {d:6.1f}  {a} -> {b}")


if __name__ == "__main__":
    main()
