// GENERATED by export_placement.py - do not edit by hand.
// City: vancouver. LED index = position in data chain.
#pragma once

const uint16_t NUM_LEDS = 68;

const int LINE_EXPO_PRODUCTION_WAY_COUNT = 20;
const int LINE_EXPO_PRODUCTION_WAY[] = {
      1, // Waterfront
      2, // Burrard
      3, // Granville
      4, // Stadium–Chinatown
      5, // Main Street–Science World
      6, // Commercial–Broadway
      7, // Nanaimo
      8, // 29th Avenue
      9, // Joyce–Collingwood
     10, // Patterson
     11, // Metrotown
     12, // Royal Oak
     13, // Edmonds
     14, // 22nd Street
     15, // New Westminster
     16, // Columbia
     29, // Sapperton
     30, // Braid
     31, // Lougheed Town Centre
     32, // Production Way–University
};

const int LINE_EXPO_LANGLEY_CITY_CENTRE_COUNT = 28;
const int LINE_EXPO_LANGLEY_CITY_CENTRE[] = {
      1, // Waterfront
      2, // Burrard
      3, // Granville
      4, // Stadium–Chinatown
      5, // Main Street–Science World
      6, // Commercial–Broadway
      7, // Nanaimo
      8, // 29th Avenue
      9, // Joyce–Collingwood
     10, // Patterson
     11, // Metrotown
     12, // Royal Oak
     13, // Edmonds
     14, // 22nd Street
     15, // New Westminster
     16, // Columbia
     17, // Scott Road
     18, // Gateway
     19, // Surrey Central
     20, // King George
     21, // Green Timbers
     22, // 152 Street
     23, // Fleetwood
     24, // Bakerview
     25, // Hillcrest
     26, // Clayton
     27, // Willowbrook
     28, // Langley City Centre
};

const int LINE_MILLENNIUM_COUNT = 23;
const int LINE_MILLENNIUM[] = {
     52, // Arbutus
     51, // South Granville
     50, // Oak–VGH
     49, // Broadway–City Hall
     48, // Mount Pleasant
     47, // Great Northern Way–Emily Carr
     46, // VCC–Clark
      6, // Commercial–Broadway
     45, // Renfrew
     44, // Rupert
     43, // Gilmore
     42, // Brentwood Town Centre
     41, // Holdom
     40, // Sperling–Burnaby Lake
     39, // Lake City Way
     32, // Production Way–University
     31, // Lougheed Town Centre
     33, // Burquitlam
     34, // Moody Centre
     35, // Inlet Centre
     36, // Coquitlam Central
     37, // Lincoln
     38, // Lafarge Lake–Douglas
};

const int LINE_CANADA_YVR_COUNT = 13;
const int LINE_CANADA_YVR[] = {
      1, // Waterfront
     53, // Vancouver City Centre
     54, // Yaletown–Roundhouse
     55, // Olympic Village
     49, // Broadway–City Hall
     56, // King Edward
     57, // Oakridge–41st Avenue
     58, // Langara–49th Avenue
     59, // Marine Drive
     60, // Bridgeport
     61, // Templeton
     62, // Sea Island Centre
     63, // YVR–Airport
};

const int LINE_CANADA_RICHMOND_BRIGHOUSE_COUNT = 14;
const int LINE_CANADA_RICHMOND_BRIGHOUSE[] = {
      1, // Waterfront
     53, // Vancouver City Centre
     54, // Yaletown–Roundhouse
     55, // Olympic Village
     49, // Broadway–City Hall
     56, // King Edward
     57, // Oakridge–41st Avenue
     58, // Langara–49th Avenue
     59, // Marine Drive
     60, // Bridgeport
     64, // Capstan
     65, // Aberdeen
     66, // Lansdowne
     67, // Richmond–Brighouse
};

const int LINE_SEABUS_COUNT = 1;
const int LINE_SEABUS[] = {
      0, // SeaBus
};
