M48
; DRILL file {KiCad 7.0.1} date Sun Sep 17 14:31:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-17T14:31:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.8661Y-0.8661
X0.8661Y-7.4803
X11.8898Y-0.8661
X11.8898Y-7.4803
T0
M30
